#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRLeft,         sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     Compass,        sensorI2CHiTechnicCompass)
#pragma config(Sensor, S4,     HTSPB,          sensorI2CCustom9V)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     Right,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Left,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     Intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     none,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     Conveyor,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     Lift,          tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    Gripper,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    lock,                 tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("debugStream")
#pragma DebuggerWindows("nxtLCDscreen")

#include "drivers/PID.h"
void Drive(int distance, int power)
{
	int C=2*(PI)*2;
	int Target= (1120/C)*distance;//en/in
	nMotorEncoder[Right]=0;
	if(distance>1)//forwards
	{
		while(nMotorEncoder[Right]<=Target)
		{
		writeDebugStreamLine("Value :%i, Target: %i",nMotorEncoder[Right], Target);
		motor[Right]=PID(Target, nMotorEncoder[Right]);
		motor[Left]=PID(Target, nMotorEncoder[Left]);
		}
		motor[Right]=0;
		motor[Left]=0;
	}
	else if(distance<1)//backwards
	{
		while(nMotorEncoder[Right]>=Target)
		{
		writeDebugStreamLine("Value :%i, Target: %i",nMotorEncoder[Right]*-1, Target);
		motor[Right]=PID(Target, nMotorEncoder[Right]);
		motor[Left]=PID(Target, nMotorEncoder[Left]);
		}
		motor[Right]=0;
		motor[Left]=0;
	}
}
task main()
{
clearDebugStream();
Drive(25,100);
}
