#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRLeft,         sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     Compass,        sensorI2CHiTechnicCompass)
#pragma config(Sensor, S4,     HTSPB,          sensorI2CCustom9V)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     Right,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Left,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     Intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     none,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     Conveyor,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     Lift,          tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    Gripper,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    lock,                 tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void Turn(int Angle)//clockwise is negitive
{

	float circumfrence = 2*(PI)*2;
	int ppr = 1120;
	int enc_in=ppr/circumfrence;//result
  nMotorEncoder[motorE]=0;
  nMotorEncoder[motorD]=0;
	float WheelbaseRadius = 7.3875;



//	writeDebugStreamLine("Target:%i",Target);

  //1/2 rot= 45deg = 1120enc
	if(Angle<0)//negitive angle
	{
		float ArcLength=degreesToRadians(abs(Angle))*WheelbaseRadius;//result
		int Target= -1*round(ArcLength*enc_in);//goal
		writeDebugStreamLine("Target:%i",Target);
		//left
		while(nMotorEncoder[motorE]>= Target)
		{
			writeDebugStreamLine("Value :%i, Target: %i",nMotorEncoder[motorE], Target);
			motor[Right]=100;
			motor[Left]=-100;
		}
		motor[Right]=0;
		motor[Left]=0;
	}
	else if(Angle>0)
	{
		float ArcLength=degreesToRadians(abs(Angle))*WheelbaseRadius;//result
		int Target= round(ArcLength*enc_in);//goal
		writeDebugStreamLine("Target:%i",Target);
	//right
		while(nMotorEncoder[motorE]<= Target)
		{
		writeDebugStreamLine("Value :%i, Target: %i",nMotorEncoder[motorE], Target);
		motor[Right]=-100;
		motor[Left]=100;
		}
		motor[Right]=0;
		motor[Left]=0;
	}
}
task main()
{
	clearDebugStream();
	Turn(90);
	wait10msec(300);
	Turn(-90);
}
